[#function convertType type language]
  [#if language == "csharp"]
    [#if type == "UUID"]
      [#return "Guid"/]
    [/#if]
  [#elseif language == "js"]
    [#if type == "UUID" || type == "String"]
      [#return "string"/]
    [#else]
      [#return "Object"/]
    [/#if]
  [/#if]
  [#return type/]
[/#function]

[#function methodParameters api language]
  [#local result = []]
  [#list api.params as param]
    [#if !param.constant??]
      [#local result = result + [(language == "js")?then(param.name, convertType(param.javaType, language) + " " + param.name)]/]
    [/#if]
  [/#list]
  [#return result?join(", ")/]
[/#function]